name: build and push image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  build-and-push:
    runs_on: ubuntu:latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: push image to dockerhub 
        env: 
          Repository: nginx
          IMAGE_TAG: latest 
        run: |
          docker build -t ${{DOCKERHUB_USERNAME}}/$REPOSITORY:$IMAGE_TAG .
          docker push ${{DOCKERHUB_USERNAME}}/$REPOSITORY:$IMAGE_TAG
